#+BEGIN_SRC emacs-lisp :exports none  :results none :eval always
(add-to-list 'org-latex-classes
             '("acmart" "\\documentclass{acmart}"
               ("\\section{%s}" . "\\section*{%s}")
               ("\\subsection{%s}" . "\\subsection*{%s}")
               ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
               ("\\paragraph{%s}" . "\\paragraph*{%s}")
               ("\\subparagraph{%s}" . "\\subparagraph*{%s}")))

#+END_SRC

:PREAMBLE:
# We don’t want to override the author, date, title, table-of-contents, and header settings of the template
#+OPTIONS: author:nil date:nil title:nil toc:nil H:3
# How many section headings to support?

#+LATEX_CLASS: acmart
#+LATEX_CLASS_OPTIONS: [acmsmall,review,anonymous]
#+LaTeX_HEADER: \settopmatter{printfolios=true,printccs=false,printacmref=false}

# For double-blind review submission, w/ CCS and ACM Reference
# #+LATEX_CLASS_OPTIONS: [acmsmall,review,anonymous]
# #+LaTeX_HEADER: \settopmatter{printfolios=true}

# For single-blind review submission, w/o CCS and ACM Reference (max submission space)
# #+LATEX_CLASS_OPTIONS: [acmsmall,review]
# #+LaTeX_HEADER: \settopmatter{printfolios=true,printccs=false,printacmref=false}

# For single-blind review submission, w/ CCS and ACM Reference
# #+LATEX_CLASS_OPTIONS: [acmsmall,review]{acmart}
# #+LaTeX_HEADER: \settopmatter{printfolios=true}

# For final camera-ready submission, w/ required CCS and ACM Reference
# #+LATEX_CLASS_OPTIONS: [acmsmall]{acmart}
# #+LaTeX_HEADER: \settopmatter{}


# Journal information
# Supplied to authors by publisher for camera-ready submission; use defaults for review submission.
#+LaTeX_HEADER: \acmJournal{PACMPL}
#+LaTeX_HEADER: \acmVolume{1}
#+LaTeX_HEADER: \acmNumber{CONF} % CONF = POPL or ICFP or OOPSLA
#+LaTeX_HEADER: \acmArticle{1}
#+LaTeX_HEADER: \acmYear{2018}
#+LaTeX_HEADER: \acmMonth{1}
#+LaTeX_HEADER: \acmDOI{} % \acmDOI{10.1145/nnnnnnn.nnnnnnn}
#+LaTeX_HEADER: \startPage{1}

# Copyright information
# Supplied to authors (based on authors' rights management selection;
# see authors.acm.org) by publisher for camera-ready submission;
# use 'none' for review submission.
#+LaTeX_HEADER: \setcopyright{none}
#+LaTeX_HEADER: %\setcopyright{acmcopyright}
#+LaTeX_HEADER: %\setcopyright{acmlicensed}
#+LaTeX_HEADER: %\setcopyright{rightsretained}
#+LaTeX_HEADER: %\copyrightyear{2018}           %% If different from \acmYear

# Bibliography style
#+LaTeX_HEADER: \bibliographystyle{ACM-Reference-Format}
# Citation style
# Note: author/year citations are required for papers published as an
# issue of PACMPL.
#+LaTeX_HEADER: \citestyle{acmauthoryear}   %% For author/year citations


#+LaTeX_HEADER: %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# Note: Authors migrating a paper from PACMPL format to traditional
# SIGPLAN proceedings format must update the '\documentclass' and
# topmatter commands above; see 'acmart-sigplanproc-template.tex'.
#+LaTeX_HEADER: %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


# Some recommended packages.
#+LaTeX_HEADER: \usepackage{booktabs}   %% For formal tables:
#+LaTeX_HEADER:                         %% http://ctan.org/pkg/booktabs
#+LaTeX_HEADER: \usepackage{subcaption} %% For complex figures with subfigures/subcaptions
#+LaTeX_HEADER:                         %% http://ctan.org/pkg/subcaption

#+BEGIN_EXPORT latex
%% Title information
\title[Short Title]{Full Title}         %% [Short Title] is optional;
                                        %% when present, will be used in
                                        %% header instead of Full Title.
\titlenote{with title note}             %% \titlenote is optional;
                                        %% can be repeated if necessary;
                                        %% contents suppressed with 'anonymous'
\subtitle{Subtitle}                     %% \subtitle is optional
\subtitlenote{with subtitle note}       %% \subtitlenote is optional;
                                        %% can be repeated if necessary;
                                        %% contents suppressed with 'anonymous'


%% Author information
%% Contents and number of authors suppressed with 'anonymous'.
%% Each author should be introduced by \author, followed by
%% \authornote (optional), \orcid (optional), \affiliation, and
%% \email.
%% An author may have multiple affiliations and/or emails; repeat the
%% appropriate command.
%% Many elements are not rendered, but should be provided for metadata
%% extraction tools.
%%
%% Author with single affiliation.
\author{First1 Last1}
\authornote{with author1 note}          %% \authornote is optional;
                                        %% can be repeated if necessary
%% \orcid{nnnn-nnnn-nnnn-nnnn}             %% \orcid is optional
\affiliation{
  \position{Position1}
  \department{Department1}              %% \department is recommended
  \institution{Institution1}            %% \institution is required
  \streetaddress{Street1 Address1}
  \city{City1}
  \state{State1}
  \postcode{Post-Code1}
  \country{Country1}                    %% \country is recommended
}
\email{first1.last1@inst1.edu}          %% \email is recommended

%% Author with two affiliations and emails.
\author{First2 Last2}
\authornote{with author2 note}          %% \authornote is optional;
                                        %% can be repeated if necessary
%% \orcid{nnnn-nnnn-nnnn-nnnn}             %% \orcid is optional
\affiliation{
  \position{Position2a}
  \department{Department2a}             %% \department is recommended
  \institution{Institution2a}           %% \institution is required
  \streetaddress{Street2a Address2a}
  \city{City2a}
  \state{State2a}
  \postcode{Post-Code2a}
  \country{Country2a}                   %% \country is recommended
}
\email{first2.last2@inst2a.com}         %% \email is recommended
\affiliation{
  \position{Position2b}
  \department{Department2b}             %% \department is recommended
  \institution{Institution2b}           %% \institution is required
  \streetaddress{Street3b Address2b}
  \city{City2b}
  \state{State2b}
  \postcode{Post-Code2b}
  \country{Country2b}                   %% \country is recommended
}
\email{first2.last2@inst2b.org}         %% \email is recommended


%% Abstract
%% Note: \begin{abstract}...\end{abstract} environment must come
%% before \maketitle command
\begin{abstract}
Text of abstract \ldots.
\end{abstract}


%% 2012 ACM Computing Classification System (CSS) concepts
%% Generate at 'http://dl.acm.org/ccs/ccs.cfm'.
\begin{CCSXML}
<ccs2012>
<concept>
<concept_id>10011007.10011006.10011008</concept_id>
<concept_desc>Software and its engineering~General programming languages</concept_desc>
<concept_significance>500</concept_significance>
</concept>
<concept>
<concept_id>10003456.10003457.10003521.10003525</concept_id>
<concept_desc>Social and professional topics~History of programming languages</concept_desc>
<concept_significance>300</concept_significance>
</concept>
</ccs2012>
\end{CCSXML}

\ccsdesc[500]{Software and its engineering~General programming languages}
\ccsdesc[300]{Social and professional topics~History of programming languages}
% End of generated code


%% Keywords
%% comma separated list
\keywords{keyword1, keyword2, keyword3}  %% \keywords are mandatory in final camera-ready submission


\maketitle
%% Note: \maketitle command must come after title commands, author
%% commands, abstract environment, Computing Classification System
%% environment and commands, and keywords command.
#+END_EXPORT
:END:

* Introduction
Text of paper...

#+BEGIN_EXPORT latex

\begin{acks}                            %% acks environment is optional
                                        %% contents suppressed with 'anonymous'
  %% Commands \grantsponsor{<sponsorID>}{<name>}{<url>} and
  %% \grantnum[<url>]{<sponsorID>}{<number>} should be used to
  %% acknowledge financial support and will be used by metadata
  %% extraction tools.
  This material is based upon work supported by the
  \grantsponsor{GS100000001}{National Science
    Foundation}{http://dx.doi.org/10.13039/100000001} under Grant
  No.~\grantnum{GS100000001}{nnnnnnn} and Grant
  No.~\grantnum{GS100000001}{mmmmmmm}.  Any opinions, findings, and
  conclusions or recommendations expressed in this material are those
  of the author and do not necessarily reflect the views of the
  National Science Foundation.
\end{acks}


%% Bibliography
%\bibliography{bibfile}


%% Appendix
\appendix
\section{Appendix}

Text of appendix \ldots
#+END_EXPORT


# Local Variables:
# org-export-before-parsing-hook: org-babel-execute-buffer
# org-latex-default-packages-alist: nil
# org-latex-packages-alist: nil
# org-latex-with-hyperref: nil
# End:
